spring.application.name=Fynex

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/finance_dashboard
spring.datasource.username=root
spring.datasource.password=Abhinesh@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080

# JWT
jwt.secret=3f8d2a1b9c4e6f7a0d5b8e2c1a4f9d3b7e0c5a8f2d1b6e9c3a0f7d4b1e8c5a2
jwt.expiration=86400000